extends: gpt2_base

model:
  name: gpt
  modules:
    transformer:
      dim: 1024           # emb_dim
      n_layers: 24
      n_heads: 16
      qkv_bias: true

train:
  run_name: gpt2-medium
  output_dir: outputs/gpt2-medium
  # Data settings for SFT
  data_dir: data/datasets/sft
  data_loader:
    kind: sft_json
    block_size: 1024
    shuffle: true
    num_workers: 0
    pin_memory: true
    drop_last: true
  # Optionally adjust batch size if memory constrained
  # batch_size: 2
